Querdos\ChallengeMe\UserBundle\Entity\PrivateMessage:
    type:             entity
    table:            cm_admin_private_message
    repositoryClass: Querdos\ChallengeMe\UserBundle\Repository\PrivateMessageRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        content:
            type:     text
            nullable: false
            unique:   false
        sent:
            type:     datetime
            nullable: false
            unique:   false

    manyToOne:
        author:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Administrator
            mappedBy:     author

        recipient:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Administrator
            mappedBy:     recipient

    lifecycleCallbacks: {  }
