Querdos\ChallengeMe\UserBundle\Entity\Team:
    type:             entity
    table:            cm_user_team
    repositoryClass:  Querdos\ChallengeMe\UserBundle\Repository\TeamRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        name:
            type:         string
            length:       255
            unique:       true
            nullable:     false
        points:
            type:         integer
            nullable:     false
            unique:       false
        created:
            type:         datetime
            nullable:     false
            unique:       false
        avatarName:
            type:         string
            length:       255
            nullable:     true
            unique:       false
        updatedAt:
            type:         datetime
            nullable:     true
            unique:       false

    oneToMany:
        players:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Player
            mappedBy:     team
            cascade:      [ "persist" ]

    oneToOne:
        leader:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Player
            cascade:      [ "persist" ]
            joinColumn:
                name:                 leader
                referencedColumnName: id
                onDelete:             cascade
                nullable:             false

    lifecycleCallbacks: {  }
