Querdos\ChallengeMe\ChallengesBundle\Entity\Challenge:
    type:             entity
    table:            cm_chal_challenge
    repositoryClass:  Querdos\ChallengeMe\ChallengesBundle\Repository\ChallengeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type:     string
            length:   255
            unique:   false
            nullable: false
        points:
            type:     integer
            unique:   false
            nullable: false
        level:
            type:     integer
            unique:   false
            nullable: false
        description:
            type:     string
            length:   255
            unique:   false
            nullable: false
        statement:
            type:     text
            unique:   false
            nullable: false
        created:
            type:     datetime
            nullable: false
            unique:   false

    oneToMany:
        resources:
            targetEntity:     Querdos\ChallengeMe\ChallengesBundle\Entity\ChallengeResource
            cascade:          [ "persist", "remove" ]
            mappedBy:         challenge

    oneToOne:
        solution:
            targetEntity:     Querdos\ChallengeMe\ChallengesBundle\Entity\ChallengeSolution
            cascade:          [ "persist", "remove" ]
            joinColumn:
                nullable:     false

    manyToOne:
        category:
            targetEntity:     Querdos\ChallengeMe\ChallengesBundle\Entity\Category
            joinColumn:
                nullable:     false

        author:
            targetEntity:     Querdos\ChallengeMe\UserBundle\Entity\Administrator
            inversedBy:       challenges
            joinColumn:
                nullable:     false

    lifecycleCallbacks: {  }
