Querdos\ChallengeMe\ChallengesBundle\Entity\ChallengeResource:
    type:             entity
    table:            cm_chal_challenge_resource
    repositoryClass:  Querdos\ChallengeMe\ChallengesBundle\Repository\ChallengeResourceRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        resourceName:
            type:         string
            length:       255
            unique:       true
            nullable:     false
        updatedAt:
            type:         datetime
            unique:       false
            nullable:     true

    manyToOne:
        uploadedBy:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Administrator
            cascade:      [ "persist" ]
            inversedBy:   resources
            joinColumn:
                nullable: false

        challenge:
            targetEntity: Querdos\ChallengeMe\ChallengesBundle\Entity\Challenge
            cascade:      [ "persist" ]
            inversedBy:   resources
            joinColumn:
                nullable: false