services:
    challengeme.manager.notification:
        class:    Querdos\ChallengeMe\PlayerBundle\Manager\NotificationManager
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager'            ] ]
            - [ setRepository,    [ '@challengeme.repository.notification'    ] ]

    challengeme.manager.player_activity:
        class:    Querdos\ChallengeMe\PlayerBundle\Manager\PlayerActivityManager
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager'             ] ]
            - [ setRepository,    [ '@challengeme.repository.player_activity'  ] ]