##################
#   Main pages   #
##################
player_homepage:
    path:     /
    defaults: { _controller: PlayerBundle:Player:index }
    methods:
        - GET

player_players_list:
    path:     /challengers
    defaults: { _controller: PlayerBundle:Player:playersList }
    methods:
        - GET

player_teams_list:
    path:     /teams
    defaults: { _controller: PlayerBundle:Player:teamsList }
    methods:
        - GET

player_my_team:
    path:     /my-team
    defaults: { _controller: PlayerBundle:Player:myTeam }
    methods:
        - GET
        - POST

######################
# SecurityController #
######################
player_login:
    path:     /login
    defaults: { _controller: PlayerBundle:Security:login }

player_login_check:
    path:     /login_check
    defaults: { _controller: PlayerBundle:Security:loginCheck }

player_logout:
    path:     /logout
    defaults: { _controller: PlayerBundle:Security:logout }