##################
#   Main pages   #
##################
player_homepage:
    path:     /
    defaults: { _controller: PlayerBundle:Player:index }

player_players_list:
    path:     /challengers
    defaults: { _controller: PlayerBundle:Player:playersList }

######################
# SecurityController #
######################
player_login:
    path:     /login
    defaults: { _controller: PlayerBundle:Security:login }

player_login_check:
    path:     /login_check
    defaults: { _controller: PlayerBundle:Security:loginCheck }

player_logout:
    path:     /logout
    defaults: { _controller: PlayerBundle:Security:logout }