##################
#   Main pages   #
##################
player_homepage:
    path:     /
    defaults: { _controller: PlayerBundle:Player:index }
    methods:
        - GET

player_players_list:
    path:     /challengers
    defaults: { _controller: PlayerBundle:Player:playersList }
    methods:
        - GET

player_teams_list:
    path:     /teams
    defaults: { _controller: PlayerBundle:Player:teamsList }
    methods:
        - GET

player_my_team:
    path:     /my-team
    defaults: { _controller: PlayerBundle:Player:myTeam }
    methods:
        - GET
        - POST

player_edit_demand:
    path:     /my-team/edit-demand/{demandId}/status/{status}
    defaults: { _controller: PlayerBundle:Player:editDemand }
    methods:
        - GET

player_clear_demand:
    path:     /my-team/clear-demand/{demandId}
    defaults: { _controller: PlayerBundle:Player:clearDemand }
    methods:
        - GET

player_remove_from_team:
    path:     /my-team/remove-from-team/{playerId}
    defaults: { _controller: PlayerBundle:Player:removePlayerFromTeam }
    methods:
        - GET

######################
# SecurityController #
######################
player_login:
    path:     /login
    defaults: { _controller: PlayerBundle:Security:login }

player_login_check:
    path:     /login_check
    defaults: { _controller: PlayerBundle:Security:loginCheck }

player_logout:
    path:     /logout
    defaults: { _controller: PlayerBundle:Security:logout }