services:
    challengeme.provider.player:
        class: Querdos\ChallengeMe\PlayerBundle\Security\Provider\PlayerProvider
        calls:
            - [ setPlayerManager, ['@challengeme.manager.player']]

    challengeme.player.form_authenticator:
        class: Querdos\ChallengeMe\PlayerBundle\Security\Authenticator\FormAuthenticator
        calls:
            - [ setContainer, [ '@service_container' ]]
            - [ setRouter,    [ '@router' ]]