assetic:
    assets:
        # Javascripts
        jquery_js:
            inputs:
                - 'assets/vendor/jquery/dist/jquery.min.js'
            output: 'assets/js/jquery.js'

        bootstrap_js:
            inputs:
                - 'assets/vendor/bootstrap/dist/js/bootstrap.min.js'
            output: 'assets/js/bootstrap.js'

        bootstrapWYSIWYG_js:
            inputs:
                - 'assets/vendor/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js'
                - 'assets/vendor/jquery.hotkeys/jquery.hotkeys.js'
                - 'assets/vendor/google-code-prettify/src/prettify.js'
            output: 'assets/js/bootstrapwysiyg.js'

        fastclick_js:
            inputs:
                - 'assets/vendor/fastclick/lib/fastclick.js'
            output: 'assets/js/fastclick.js'

        nprogress_js:
            inputs:
                - 'assets/vendor/nprogress/nprogress.js'
            output: 'assets/js/nprogress.js'

        charts_js:
            inputs:
                - 'assets/vendor/Chart.js/dist/Chart.min.js'
            output: 'assets/js/chart.js'

        gauge_js:
            inputs:
                - 'assets/vendor/gauge.js/dist/gauge.min.js'
            ouput: 'assets/js/gauge.js'

        bootstrap_progressbar_js:
            inputs:
                - 'assets/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js'
            output: 'assets/js/progressbar.js'

        iCheck_js:
            inputs:
                - 'assets/vendor/iCheck/icheck.min.js'
            output: 'assets/js/icheck.js'

        skycons_js:
            inputs:
                - 'assets/vendor/skycons/skycons.js'
            output: 'assets/js/skycons.js'

        flot_js:
            inputs:
                - 'assets/vendor/Flot/jquery.flot.js'
                - 'assets/vendor/Flot/jquery.flot.pie.js'
                - 'assets/vendor/Flot/jquery.flot.time.js'
                - 'assets/vendor/Flot/jquery.flot.stack.js'
                - 'assets/vendor/Flot/jquery.flot.resize.js'
            output: 'assets/js/flot.js'

        morris_js:
            inputs:
                - 'assets/vendor/raphael/raphael.min.js'
                - 'assets/vendor/morris.js/morris.min.js'
            output: 'assets/js/morris.js'

        # Stylesheets
        bootstrap:
            inputs:
                - 'assets/vendor/bootstrap/dist/css/bootstrap.min.css'
            output: 'assets/css/boostrap.css'

        bootstrapWYSIWYG_css:
            inputs:
                - 'assets/vendor/google-code-prettify/bin/prettify.min.css'
            output: 'assets/css/bootstrapwysiwyg.css'

        fontAwesome:
            inputs:
                - 'assets/vendor/font-awesome/css/font-awesome.min.css'
            output: 'assets/css/fontAwesome.css'

        iCheck:
            inputs:
                - 'assets/vendor/iCheck/skins/flat/green.css'
            output: 'assets/css/icheck.css'

        bootstrap_progressBar:
            inputs:
                - 'assets/vendor/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'
            output: 'assets/css/bootstrap-progressbar.css'