challenges:
    resource: "@ChallengesBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

landing:
    resource: "@LandingBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /administration