security:
    encoders:
        Querdos\ChallengeMe\AdministratorBundle\Entity\Administrator:
            algorithm: bcrypt
            cost: 12

        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        administrator_provider:
            id: challengeme.provider.admin

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/(.*)/login$
            anonymous: ~

        admin_firewall:
            pattern:  ^/admin
#            guard:
#                authenticators:
#                    - challengeme.authenticator.admin
            provider: administrator_provider
            form_login:
                login_path:           admin_login
                check_path:           admin_login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path:  admin_homepage
                failure_path:         admin_login
            logout:
                path:   /admin/logout
                target: /admin/login

        landing_firewall:
            pattern:    ^/
            anonymous:  ~

    access_control:
        - { path: ^/(.*)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,           roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,      roles: ROLE_ADMIN }
