security:
    encoders:
        Querdos\ChallengeMe\AdministratorBundle\Entity\Administrator:
            algorithm:  bcrypt
            cost:       12

        Querdos\ChallengeMe\AdministratorBundle\Entity\Moderator:
            algorithm:  bcrypt
            cost:       12

        Symfony\Component\Security\Core\User\User:
            algorithm:  bcrypt
            cost:       12

    providers:
        administrator_provider:
            id: challengeme.provider.admin
        moderator_provider:
            id: challengeme.provider.moderator
        redactor_provider:
            id: challengeme.provider.redactor

    role_hierarchy:
        ROLE_REDACTOR:      [ROLE_USER]
        ROLE_MODERATOR:     [ROLE_USER, ROLE_REDACTOR]
        ROLE_ADMIN:         [ROLE_USER, ROLE_MODERATOR, ROLE_REDACTOR]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall for the login route
        login_firewall:
            pattern: ^/(.*)/(.*)/login$
            anonymous: ~

        # Firewall for the restricted area - Admin
        admin_firewall:
            pattern:  ^/restricted/admin
#            guard:
#                authenticators:
#                    - challengeme.authenticator.admin
            provider: administrator_provider
            form_login:
                login_path:           admin_login
                check_path:           admin_login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path:  admin_homepage
                failure_path:         admin_login
            logout:
                path:                 /restricted/admin/logout
                target:               /restricted/admin/login

        moderator_firewall:
            pattern:                  ^/restricted/moderator
            provider:                 moderator_provider
            form_login:
                login_path:           moderator_login
                check_path:           moderator_login_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path:  moderator_homepage
                failure_path:         moderator_login
            logout:
                path:                 /restricted/moderator/logout
                target:               /restricted/moderator/login

        landing_firewall:
            pattern:                  ^/
            anonymous:                ~

    access_control:
        - { path: ^/(.*)/login,             roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,                       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/restricted/admin,       roles: ROLE_ADMIN }
        - { path: ^/restricted/moderator,   roles: ROLE_MODERATOR }
