services:
    challengeme.manager.administrator:
        class: Querdos\ChallengeMe\UserBundle\Manager\AdministratorManager
        calls:
            - [ setRepository,      ['@challengeme.repository.administrator'] ]
            - [ setPasswordEncoder, ['@security.password_encoder'] ]
            - [ setEntityManager,   ['@doctrine.orm.entity_manager'] ]
            - [ setRoleManager,     ['@challengeme.manager.role'] ]

    challengeme.manager.personal_information:
        class: Querdos\ChallengeMe\UserBundle\Manager\PersonalInformationManager
        calls:
            - [ setRepository,      ['@challengeme.repository.personal_information'] ]

    challengeme.manager.role:
        class: Querdos\ChallengeMe\UserBundle\Manager\RoleManager
        calls:
            -  [ setRepository,     [ '@challengeme.repository.role' ] ]

    challengeme.manager.private_message:
        class: Querdos\ChallengeMe\UserBundle\Manager\PrivateMessageManager
        calls:
            - [ setRepository,      [ '@challengeme.repository.private_message' ] ]
            - [ setAdminManager,    [ '@challengeme.manager.administrator' ] ]
            - [ setEntityManager,   [ '@doctrine.orm.entity_manager' ] ]

    challengeme.manager.player:
        class: Querdos\ChallengeMe\UserBundle\Manager\PlayerManager
        calls:
            - [ setRepository,              [ '@challengeme.repository.player'        ] ]
            - [ setEntityManager,           [ '@doctrine.orm.entity_manager'          ] ]
            - [ setPasswordEncoder,         [ '@security.password_encoder'            ] ]
            - [ setChallengeSolvingManager, ['@challengeme.manager.challenge_solving' ] ]

    challengeme.manager.team:
        class: Querdos\ChallengeMe\UserBundle\Manager\TeamManager
        calls:
            - [ setRepository,      [ '@challengeme.repository.team' ]]
            - [ setEntityManager,   [ '@doctrine.orm.entity_manager' ]]

    challengeme.manager.demand:
        class: Querdos\ChallengeMe\UserBundle\Manager\DemandManager
        calls:
            - [ setRepository,      [ '@challengeme.repository.demand'  ]]
            - [ setEntityManager,   [ '@doctrine.orm.entity_manager'    ]]
            - [ setPlayerManager,   [ '@challengeme.manager.demand'     ]]

    challengeme.manager.player_role:
        class: Querdos\ChallengeMe\UserBundle\Manager\PlayerRoleManager
        calls:
            - [ setRepository,      [ '@challengeme.repository.player_role' ]]
            - [ setEntityManager,   [ '@doctrine.orm.entity_manager'    ]]

