Querdos\ChallengeMe\PlayerBundle\Entity\TeamActivity:
    type:             entity
    table:            cm_player_team_activity
    repositoryClass:  Querdos\ChallengeMe\PlayerBundle\Repository\TeamActivityRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        title:
            type:         string
            length:       255
            unique:       false
            nullable:     false
        description:
            type:         text
            unique:       false
            nullable:     false
        date:
            type:         datetime
            unique:       false
            nullable:     false

    manyToOne:
        team:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Team
            cascade:      [ "persist" ]
            joinColumn:
                nullable: false

    lifecycleCallbacks: {}
