assetic:
    assets:
        jVectorMap:
            inputs:
                - 'bundles/admin/css/maps/jquery-jvectormap-2.0.3.css'
            output: 'assets/admin/css/jvectormap.css'

        customTheme_css:
            inputs:
                - 'bundles/admin/css/custom.css'
            output: 'assets/admin/css/custom.css'