assetic:
    assets:
        flot_plugin_js:
            inputs:
                - '@AdminBundle/Resources/public/js/flot/jquery.flot.orderBars.js'
                - '@AdminBundle/Resources/public/js/flot/date.js'
                - '@AdminBundle/Resources/public/js/flot/jquery.flot.spline.js'
                - '@AdminBundle/Resources/public/js/flot/curvedLines.js'
            output: 'assets/admin/js/flot_plugin.js'

        jVectorMap_js:
            inputs:
                - '@AdminBundle/Resources/public/js/maps/jquery-jvectormap-2.0.3.min.js'
                - '@AdminBundle/Resources/public/js/maps/jquery-jvectormap-world-mill-en.js'
                - '@AdminBundle/Resources/public/js/maps/jquery-jvectormap-us-aea-en.js'
                - '@AdminBundle/Resources/public/js/maps/gdp-data.js'
            output: 'assets/admin/js/jvectormap.js'

        bootstrapDateRangePicker_js:
            inputs:
                - '@AdminBundle/Resources/public/js/moment/moment.min.js'
                - '@AdminBundle/Resources/public/js/datepicker/daterangepicker.js'
            output: 'assets/admin/js/bootstrapdaterangepicker.js'

        customTheme_js:
            inputs:
                - '@AdminBundle/Resources/public/js/custom.js'
            output: 'assets/admin/js/customTheme.js'