services:
    app.locale_listener:
        class: Querdos\ChallengeMe\AdministratorBundle\EventListener\LocaleListener
        calls:
            - [ setDefaultLocale, ['%kernel.default_locale%']]
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: Querdos\ChallengeMe\AdministratorBundle\EventListener\UserLocaleListener
        calls:
            - [ setSession, ['@session'] ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

