Querdos\ChallengeMe\PlayerBundle\Entity\Notification:
    type:             entity
    table:            cm_player_notification
    repositoryClass:  Querdos\ChallengeMe\PlayerBundle\Repository\NotificationRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        content:
            type:         text
            nullable:     false
            unique:       false
        state:
            type:         boolean
            nullable:     false
            unique:       false
        created:
            type:         datetime
            nullable:     false
            unique:       false

    manyToOne:
        player:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Player
            cascade:      [ "persist" ]
            joinColumn:
                nullable: false

    lifecycleCallbacks: {}