Querdos\ChallengeMe\ChallengesBundle\Entity\Category:
    type:             entity
    table:            cm_cha_category
    repositoryClass:  Querdos\ChallengeMe\ChallengesBundle\Repository\CategoryRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO

    fields:
        title:
            type:       string
            length:     255
            nullable:   false
            unique:     true
        description:
            type:       string
            length:     255
            nullable:   false
            unique:     true
        created:
            type:       datetime
            nullable:   false
            unique:     false

    lifecycleCallbacks: {  }
