Querdos\ChallengeMe\ChallengesBundle\Entity\Rating:
    type:             entity
    table:            cm_chal_rating
    repositoryClass:  Querdos\ChallengeMe\ChallengesBundle\Repository\RatingRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        mark:
            type:         integer
            length:       1
            nullable:     false
            unique:       false

    manyToOne:
        player:
            targetEntity: Querdos\ChallengeMe\UserBundle\Entity\Player
            cascade:      [ "persist" ]
            joinColumn:
                nullable: false

        challenge:
            targetEntity: Querdos\ChallengeMe\ChallengesBundle\Entity\Challenge
            cascade:      [ "persist" ]
            joinColumn:
                nullable: false

    lifecycleCallbacks: {}