assetic:
    assets:
        jVectorMap:
            inputs:
                - 'bundles/player/css/maps/jquery-jvectormap-2.0.3.css'
            output: 'assets/player/css/jvectormap.css'

        customTheme_css:
            inputs:
                - 'bundles/player/css/custom.css'
            output: 'assets/player/css/custom.css'