assetic:
    assets:
        html5Shiv_js:
            inputs:
                - 'bundles/landing/js/html5shiv.js'
            output: 'assets/js/html5shiv.js'

        jqueryScrollTo_js:
            inputs:
                - 'bundles/landing/js/jquery.scrollTo.min.js'
            output: 'assets/js/jqueryscrollto.js'

        jqueryEasing_js:
            inputs:
                - 'bundles/landing/js/jquery.easing.1.3.js'
            output: 'assets/js/jqueryEasing.js'

        jquerySlider_js:
            inputs:
                - 'bundles/landing/js/jquery.themepunch.revolution.min.js'
                - 'bundles/landing/js/custom.js'
            output: 'assets/js/jquerySlider.js'

        jqueryLandlr_js:
            inputs: 'bundles/landing/js/jquery.js'
            output: 'assets/js/jqueryLandlr.js'

        bootstrapLandlr_js:
            inputs: 'bundles/landing/js/bootstrap.min.js'
            output: 'assets/js/bootsrapLandlr.js'

