services:
    challengeme.manager.administrator:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\AdministratorManager
        calls:
            - [ setRepository,      ['@challengeme.repository.administrator']]
            - [ setPasswordEncoder, ['@security.password_encoder']]
            - [ setEntityManager,   ['@doctrine.orm.entity_manager']]

    challengeme.manager.personal_information:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\PersonalInformationManager
        calls:
            - [ setRepository,      ['@challengeme.repository.personal_information'] ]

    challengeme.manager.role:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\RoleManager
        calls:
            -  [ setRepository,     [ '@challengeme.repository.role' ] ]