services:
    challengeme.manager.administrator:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\AdministratorManager
        calls:
            - [ setRepository,      ['@doctrine.orm.entity_manager']]
            - [ setPasswordEncoder, ['@security.password_encoder']]

    challengeme.manager.moderator:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\ModeratorManager
        calls:
            - [ setRepository,      ['@doctrine.orm.entity_manager']]
            - [ setPasswordEncoder, ['@security.password_encoder']]

    challengeme.manager.redactor:
        class: Querdos\ChallengeMe\AdministratorBundle\Manager\RedactorManager
        calls:
            - [ setRepository,      ['@doctrine.orm.entity_manager']]
            - [ setPasswordEncoder, ['@security.password_encoder']]
