services:
    challengeme.manager.database_dump:
        class:    Querdos\ChallengeMe\AdministratorBundle\Manager\DatabaseDumpManager
        calls:
            - [ setRepository,    [ '@challengeme.repository.database_dump' ] ]
            - [ setEntityManager, [ '@doctrine.orm.entity_manager'          ] ]