services:
    challengeme.manager.administrator:
        class:      Querdos\ChallengeMe\AdministratorBundle\Manager\AdministratorManager
        arguments:  [ '@doctrine.orm.entity_manager' ]
        calls:
            - [ setPasswordEncoder, ['@security.password_encoder']]

    challengeme.manager.moderator:
        class:      Querdos\ChallengeMe\AdministratorBundle\Manager\ModeratorManager
        arguments:  [ '@doctrine.orm.entity_manager' ]
        calls:
            - [ setPasswordEncoder, ['@security.password_encoder']]

    challengeme.manager.redactor:
        class:      Querdos\ChallengeMe\AdministratorBundle\Manager\RedactorManager
        arguments:  [ '@doctrine.orm.entity_manager' ]
        calls:
            - [ setPasswordEncoder, ['@security.password_encoder']]
