services:
    challengeme.repository.administrator:
        class:      Querdos\ChallengeMe\AdministratorBundle\Repository\AdministratorRepository
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:Administrator" ]
    
    challengeme.repository.info_user:
        class:      Querdos\ChallengeMe\AdministratorBundle\Repository\InfoUserRepository
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:InfoUser" ]

    challengeme.repository.personal_information:
        class:      Querdos\ChallengeMe\AdministratorBundle\Repository\PersonalInformationRepository
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:PersonalInformation" ]

    challengeme.repository.social:
        class:      Querdos\ChallengeMe\AdministratorBundle\Repository\SocialRepository
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:Social" ]

    challengeme.repository.skill:
        class:      Querdos\ChallengeMe\AdministratorBundle\Repository\SkillRepository
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:Skill" ]

    challengeme.repository.role:
        class:      Querdos\ChallengeMe\AdministratorBundle\Entity\Role
        factory:    [ "@doctrine.orm.entity_manager", "getRepository" ]
        arguments:  [ "AdminBundle:Role" ]