##################
#   Main pages   #
##################

administration_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Administration:index }
    methods:
        - GET

administration_inbox:
    path:     /inbox
    defaults: { _controller: AdminBundle:Administration:inbox }
    methods:
        - GET

administration_profile:
    path:     /profile
    defaults: { _controller: AdminBundle:Administration:profile }
    methods:
        - GET

administration_playersManagement:
    path:     /players-management
    defaults: { _controller: AdminBundle:Administration:playersManagement }
    methods:
        - GET

administration_adminsManagement:
    path:     /admins-management
    defaults: { _controller: AdminBundle:Administration:adminsManagement }
    methods:
        - GET

administration_addAdmin:
    path:     /admins-management/create
    defaults: { _controller: AdminBundle:Administration:addAdmin }
    methods:
        - GET
        - POST

administration_updateAdmin:
    path:     /admins-management/update/{id}
    defaults: { _controller: AdminBundle:Administration:updateAdmin }
    methods:
        - GET
        - POST

administration_removeAdmin:
    path:     /admins-management/remove/{id}
    defaults: { _controller: AdminBundle:Administration:removeAdmin }
    methods:
        - GET

administration_moderatorsManagement:
    path:     /moderators-management
    defaults: { _controller: AdminBundle:Administration:moderatorsManagement }
    methods:
        - GET

administration_addModerator:
    path:     /moderators-management/create
    defaults: { _controller: AdminBundle:Administration:addModerator }
    methods:
        - GET
        - POST

administration_updateModerator:
    path:     /moderators-management/update/{id}
    defaults: { _controller: AdminBundle:Administration:updateModerator }
    methods:
        - GET
        - POST

administration_removeModerator:
    path:     /moderators-management/remove/{id}
    defaults: { _controller: AdminBundle:Administration:removeModerator }
    methods:
        - GET

administration_redactorsManagement:
    path:     /redactors-management
    defaults: { _controller: AdminBundle:Administration:redactorsManagement }
    methods:
        - GET

administration_addRedactor:
    path:     /redactors-management/create
    defaults: { _controller: AdminBundle:Administration:addRedactor }
    methods:
        - GET
        - POST

administration_updateRedactor:
    path:     /redactors-mangement/update/{id}
    defaults: { _controller: AdminBundle:Administration:updateRedactor }
    methods:
        - GET
        - POST

administration_removeRedactor:
    path:     /redactors-management/remove/{id}
    defaults: { _controller: AdminBundle:Administration:removeRedactor }
    methods:
        - GET

administration_resetPassword:
    path:     /reset-password/{id}
    defaults: { _controller: AdminBundle:Administration:resetPassword }
    methods:
        - GET

########################
# ChallengesController #
########################

challenges_category_management:
    path:     /categories-management
    defaults: { _controller: AdminBundle:Challenges:categoryManagement }
    methods:
        - GET

challenges_category_add:
    path:     /categories-management/add
    defaults: { _controller: AdminBundle:Challenges:addCategory }
    methods:
        - GET
        - POST

challenges_category_update:
    path:     /categories-management/update/{id}
    defaults: { _controller: AdminBundle:Challenges:updateCategory }
    methods:
        - GET
        - POST

challenges_category_remove:
    path:     /categories_management/remove/{id}
    defaults: { _controller: AdminBundle:Challenges:removeCategory }
    methods:
        - GET
        - POST

challenges_category_details:
    path:     /{category_id}/challenges
    defaults: { _controller: AdminBundle:Challenges:categoryDetails }
    methods:
        - GET

challenges_challenge_add:
    path:     /challenges/add
    defaults: { _controller: AdminBundle:Challenges:challengeAdd }
    methods:
        - GET
        - POST

challenges_challenge_details:
    path:     /{category_id}/challenge/{challenge_id}
    defaults: { _controller: AdminBundle:Challenges:challengeDetail }
    methods:
        - GET

######################
# SecurityController #
######################

administration_login:
    path:     /login
    defaults: { _controller: AdminBundle:Security:login }

administration_login_check:
    path:     /login_check
    defaults: { _controller: AdminBundle:Security:loginCheck }

administration_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Security:logout }