###################
# AdminController #
##################

admin_homepage:
    path:     /admin/
    defaults: { _controller: AdminBundle:Admin:index }
    methods:
        - GET

admin_inbox:
    path:     /admin/inbox
    defaults: { _controller: AdminBundle:Admin:inbox }
    methods:
        - GET

admin_profile:
    path:     /admin/profile
    defaults: { _controller: AdminBundle:Admin:profile }
    methods:
        - GET

admin_playersManagement:
    path:     /admin/players-management
    defaults: { _controller: AdminBundle:Admin:playersManagement }
    methods:
        - GET

admin_adminsManagement:
    path:     /admin/admins-management
    defaults: { _controller: AdminBundle:Admin:adminsManagement }
    methods:
        - GET

admin_moderatorsManagement:
    path:     /admin/moderators-management
    defaults: { _controller: AdminBundle:Admin:moderatorsManagement }
    methods:
        - GET

admin_redactorsManagement:
    path:     /admin/redactors-management
    defaults: { _controller: AdminBundle:Admin:redactorsManagement }
    methods:
        - GET

######################
# SecurityController #
######################

# Path for ^/restricted
restricted_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Security:homepage }

# Administrator
admin_login:
    path:     /admin/login
    defaults: { _controller:  AdminBundle:Security:loginAdmin }

admin_login_check:
    path:     /admin/login_check
    defaults: { _controller:  AdminBundle:Security:loginAdminCheck }

admin_logout:
    path:     /admin/logout
    defaults: { _controller:  AdminBundle:Security:logout }

# Moderator
moderator_login:
    path:     /moderator/login
    defaults: { _controller: AdminBundle:Security:loginModerator }

moderator_login_check:
    path:     /moderator/login_check
    defaults:  { _controller: AdminBundle:Security:loginModeratorCheck }

moderator_logout:
    path:     /moderator/logout
    defaults: { _controller: AdminBundle:Security:logout }

# Redactor
redactor_login:
    path:     /redactor/login
    defaults: { _controller: AdminBundle:Security:loginRedactor }

redactor_login_check:
    path:     /redactor/login_check
    defaults: { _controller: AdminBundle:Security:loginRedactorCheck }

redactor_logout:
    path:     /redactor/logout
    defaults: { _controller: AdminBundle:Security:logout }