###################
# AdminController #
##################

admin_homepage:
    path:     /admin/
    defaults: { _controller: AdminBundle:Admin:index }
    methods:
        - GET

admin_inbox:
    path:     /admin/inbox
    defaults: { _controller: AdminBundle:Admin:inbox }
    methods:
        - GET

admin_profile:
    path:     /admin/profile
    defaults: { _controller: AdminBundle:Admin:profile }
    methods:
        - GET

admin_playersManagement:
    path:     /admin/players-management
    defaults: { _controller: AdminBundle:Admin:playersManagement }
    methods:
        - GET

admin_adminsManagement:
    path:     /admin/admins-management
    defaults: { _controller: AdminBundle:Admin:adminsManagement }
    methods:
        - GET

admin_moderatorsManagement:
    path:     /admin/moderators-management
    defaults: { _controller: AdminBundle:Admin:moderatorsManagement }
    methods:
        - GET

admin_redactorsManagement:
    path:     /admin/redactors-management
    defaults: { _controller: AdminBundle:Admin:redactorsManagement }
    methods:
        - GET

######################
# SecurityController #
######################
admin_login:
    path:     /admin/login
    defaults: { _controller: AdminBundle:Security:login }

admin_login_check:
    path:     /admin/login_check
    defaults: { _controller: AdminBundle:Security:loginCheck }

admin_logout:
    path:     /admin/logout
    defaults: { _controller: AdminBundle:Security:logout }
