###################
# AdminController #
##################

admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Admin:index }
    methods:
        - GET

admin_inbox:
    path:     /admin/inbox
    defaults: { _controller: AdminBundle:Admin:inbox }
    methods:
        - GET

admin_profile:
    path:     /admin/profile
    defaults: { _controller: AdminBundle:Admin:profile }
    methods:
        - GET

admin_playersManagement:
    path:     /admin/players-management
    defaults: { _controller: AdminBundle:Admin:playersManagement }
    methods:
        - GET

admin_adminsManagement:
    path:     /admin/admins-management
    defaults: { _controller: AdminBundle:Admin:adminsManagement }
    methods:
        - GET

admin_moderatorsManagement:
    path:     /admin/moderators-management
    defaults: { _controller: AdminBundle:Admin:moderatorsManagement }
    methods:
        - GET

admin_redactorsManagement:
    path:     /admin/redactors-management
    defaults: { _controller: AdminBundle:Admin:redactorsManagement }
    methods:
        - GET

#######################
# ModeratorController #
#######################
moderator_homepage:
    path:     /moderator
    defaults: { _controller: AdminBundle:Moderator:index}
    methods:
        - GET

######################
# RedactorController #
######################
redactor_homepage:
    path:     /redactor
    defaults: { _controller: AdminBundle:Redactor:index }
    methods:
        - GET

######################
# SecurityController #
######################

administration:
    path:     /
    defaults: { _controller: AdminBundle:Security:default}

administration_login:
    path:     /login
    defaults: { _controller: AdminBundle:Security:login }

administration_login_check:
    path:     /login_check
    defaults: { _controller: AdminBundle:Security:loginCheck }

administration_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Security:logout }