imports:
    - { resource: managers.yml }

    - { resource: assetic_js.yml }
    - { resource: assetic_css.yml }

    - { resource: validators.yml }

services:
    challengeme.provider.admin:
        class: Querdos\ChallengeMe\AdministratorBundle\Security\Provider\AdministratorProvider
        arguments: ["@challengeme.manager.administrator"]
    challengeme.provider.moderator:
        class: Querdos\ChallengeMe\AdministratorBundle\Security\Provider\ModeratorProvider
        calls:
            - [ setModeratorManager, ['@challengeme.manager.moderator']]