imports:
    - { resource: assetic_js.yml }
    - { resource: assetic_css.yml }

services:
    challengeme.provider.admin:
        class: Querdos\ChallengeMe\AdministratorBundle\Security\Provider\AdministratorProvider
        calls:
            - [ setAdminManager,      ['@challengeme.manager.administrator'] ]

    challengeme.admin.form_authenticator:
        class: Querdos\ChallengeMe\AdministratorBundle\Security\Authenticator\FormAuthenticator
        calls:
            - [ setContainer,         ['@service_container'] ]
            - [ setRouter,            ['@router'] ]