Querdos\ChallengeMe\AdministratorBundle\Entity\Administrator:
    properties:
        username:
            - NotNull:
                message:    "Username is mandatory"
            - Length:
                min:        4
                max:        128
                minMessage: "Username must be at least {{ limit }} characters long"
                maxMessage: "Username cannot be longer than {{ limit }} characters"
            - Querdos\ChallengeMe\AdministratorBundle\Validator\Constraints\UsernameExists: ~
        password:
            - Length:
                min:        8
                max:        255
                minMessage: "Password must be at least {{ limit }} characters long"
                maxMessage: "Password cannot be longer than {{ limit }} characters"
        email:
            - NotBlank:
                message:    "Email is mandatory"
            - Email:
                message:    "The email {{ value }} is not a valid email"
                checkMX:    true
            - Querdos\ChallengeMe\AdministratorBundle\Validator\Constraints\EmailExists: ~
        emailBack:
            - NotNull:
                message:    "Secondary email cannot be null"
            - Email:
                message:    "The email {{ value }} is not a valid email"
                checkMX:    true
            - Querdos\ChallengeMe\AdministratorBundle\Validator\Constraints\EmailExists: ~
        infoUser:
            - Valid:        ~
    getters:
        emailCorrect:
            - 'IsTrue': { message: "Emails must be different" }
        passwordDifferentFromUsername:
            - 'IsTrue': { message: "The password cannot match the username" }

Querdos\ChallengeMe\AdministratorBundle\Entity\InfoUser:
    properties:
        firstName:
            - NotNull:
                message:    "Firstname cannot be null"
            - Length:
                min:        4
                max:        128
                minMessage: "Firstname must be at least {{ limit }} characters long"
                maxMessage: "Firstname cannot be longer than {{ limit }} characters"
        lastName:
            - NotNull:
                message:    "Lastname cannot be null"
            - Length:
                min:        4
                max:        128
                minMessage: "Lastname must be at least {{ limit }} characters long"
                maxMessage: "Lastname cannot be longer than {{ limit }} characters"

        birthday:
            - NotNull:
                message:    "Birthday cannot be null"
            - Date:
                message:    "The value for the birthday isn't a valid Date"
    getters:
        birthdayCorrect:
            - 'IsTrue': { message: "The birthday cannot be greater than today" }