services:
    challengeme.validator.admin:
        class:      Querdos\ChallengeMe\AdministratorBundle\Validator\AdminValidator
        calls:
            - [ setValidator,     ['@validator'] ]
            - [ setAdminManager,  ['@challengeme.manager.administrator'] ]