services:
    challengeme.validator.admin:
        class:      Querdos\ChallengeMe\AdministratorBundle\Validator\AdminValidator
        calls:
            - [ setValidator,         ['@validator'] ]
            - [ setAdminManager,      ['@challengeme.manager.administrator'] ]
            - [ setModeratorManager,  ['@challengeme.manager.moderator']]
    challengeme.validator.moderator:
        class:      Querdos\ChallengeMe\AdministratorBundle\Validator\ModeratorValidator
        calls:
            - [ setValidator,         ['@validator'] ]
            - [ setModeratorManager,  ['@challengeme.manager.moderator'] ]
            - [ setAdminManager,      ['@challengeme.manager.administrator'] ]