services:
    challengeme.validator.admin:
        class:      Querdos\ChallengeMe\AdministratorBundle\Validator\AdminValidator
        arguments:  ["@validator", "@challengeme.manager.administrator"]