Querdos\ChallengeMe\AdministratorBundle\Entity\InfoUser:
    type:             entity
    table:            cm_admin_infoUser
    repositoryClass:  Querdos\ChallengeMe\AdministratorBundle\Repository\InfoUserRepository
    id:
        id:
            type:       integer
            id:         true
            generator:  { strategy: AUTO }
    fields:
        firstname:
            type:       string
            length:     128
            unique:     true
            nullable:   false
        lastname:
            type:       string
            length:     128
            unique:     true
            nullable:   false
        birthday:
            type:       date
            nullable:   false