Querdos\ChallengeMe\AdministratorBundle\Entity\InfoUser:
    type:             entity
    table:            cm_admin_infoUser
    repositoryClass:  Querdos\ChallengeMe\AdministratorBundle\Repository\InfoUserRepository
    id:
        id:
            type:       integer
            id:         true
            generator:  { strategy: AUTO }
    fields:
        firstName:
            type:       string
            length:     128
            unique:     false
            nullable:   false
        lastName:
            type:       string
            length:     128
            unique:     false
            nullable:   true
        birthday:
            type:       date
            nullable:   false
        address:
            type:       string
            length:     255
            unique:     false
            nullable:   true
        locale:
            type:       string
            length:     2
            unique:     false
            nullable:   false