Querdos\ChallengeMe\AdministratorBundle\Entity\Moderator:
    type:             entity
    table:            cm_admin_moderator
    repositoryClass:  Querdos\ChallengeMe\AdministratorBundle\Repository\ModeratorRepository
    id:
        id:
            type:     integer
            id:       true
            generator:
                strategy: AUTO
    fields:
        username:
            type:     string
            length:   '128'
            unique:   true
            nullable: false
        password:
            type:     string
            length:   255
            unique:   false
            nullable: false
        email:
            type:     string
            length:   255
            unique:   true
            nullable: false
        emailBack:
            type:     string
            length:   255
            unique:   true
            nullable: false

    manyToOne:
        infoUser:
            targetEntity: Querdos\ChallengeMe\AdministratorBundle\Entity\InfoUser
            cascade:      [ "persist", "remove" ]

    lifecycleCallbacks: {  }
