Querdos\ChallengeMe\AdministratorBundle\Entity\PersonalInformation:
    type:             entity
    table:            cm_admin_personnal_info
    repositoryClass:  Querdos\ChallengeMe\AdministratorBundle\Repository\PersonalInformationRepository
    id:
        id:
            type:     integer
            id:       true
            generator:
                strategy: AUTO
    fields:
        address:
            type:     string
            length:   255
            unique:   false
            nullable: true
        job:
            type:     string
            length:   255
            unique:   false
            nullable: true
        website:
            type:     string
            length:   255
            unique:   false
            nullable: true

    oneToMany:
        socials:
            targetEntity: Querdos\ChallengeMe\AdministratorBundle\Entity\Social
            cascade:      [ "persist", "remove" ]
            mappedBy:     personalInformation

        skills:
            targetEntity: Querdos\ChallengeMe\AdministratorBundle\Entity\Skill
            cascade:      [ "persist", "remove" ]
            mappedBy:     personalInformation

    lifecycleCallbacks: {  }